Курсовая работа Витрик Григорий ИД24-1 2.2

Анализ характеристик музыкальных треков для поиска паттернов популярности и жанровой принадлежности

##Основной датасет MTG-Jamendo

In [2]:
!git clone https://github.com/MTG/mtg-jamendo-dataset.git

Cloning into 'mtg-jamendo-dataset'...
remote: Enumerating objects: 1290, done.
remote: Counting objects: 100% (260/260), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 1290 (delta 246), reused 228 (delta 226), pack-reused 1030 (from 1)
Receiving objects: 100% (1290/1290), 42.37 MiB | 17.03 MiB/s, done.
Resolving deltas: 100% (792/792), done.
Updating files: 100% (186/186), done.

In [3]:
%cd mtg-jamendo-dataset

/content/mtg-jamendo-dataset

In [4]:
!ls

audio_licenses.txt  _config.yml  derived  README.md  scripts  stats
CITATION.bib	    data	 LICENSE  results    split

In [5]:
!ls data

autotagging_genre.tsv	    download			     raw.tsv
autotagging_instrument.tsv  raw_30s_cleantags_50artists.tsv  splits
autotagging_moodtheme.tsv   raw_30s_cleantags.tsv	     tag_map.json
autotagging_top50tags.tsv   raw_30s.tsv			     tags
autotagging.tsv		    raw.meta.tsv

In [6]:
import os
import pandas as pd
import requests
import xml.etree.ElementTree as ET

In [7]:
rows = []

with open("data/autotagging_instrument.tsv", "r", encoding="utf-8") as f:
  for line in f:
    if line.startswith("#"):
      continue

    parts = line.strip().split("\t")

    rows.append(parts)

rows[:3]

[['TRACK_ID', 'ARTIST_ID', 'ALBUM_ID', 'PATH', 'DURATION', 'TAGS'],
 ['track_0000382',
  'artist_000020',
  'album_000046',
  '82/382.mp3',
  '211.1',
  'instrument---voice'],
 ['track_0000383',
  'artist_000020',
  'album_000046',
  '83/383.mp3',
  '113.1',
  'instrument---voice']]

In [8]:
data = []

for parts in rows[1:]:
    data.append({
        "track_id": parts[0],
        "artist_id": parts[1],
        "album_id": parts[2],
        "path": parts[3],
        "duration": float(parts[4]),
        "tags": parts[5:]
    })

df_instruments = pd.DataFrame(data)

df_instruments.head()

,track_id,artist_id,album_id,path,duration,tags
0,track_0000382,artist_000020,album_000046,82/382.mp3,211.1,[instrument---voice]
1,track_0000383,artist_000020,album_000046,83/383.mp3,113.1,[instrument---voice]
2,track_0000384,artist_000020,album_000046,84/384.mp3,115.7,[instrument---voice]
3,track_0000386,artist_000020,album_000046,86/386.mp3,103.4,[instrument---voice]
4,track_0000387,artist_000020,album_000046,87/387.mp3,257.1,[instrument---voice]

In [9]:
df_instruments["instruments"] = df_instruments["tags"].apply(
  lambda x: [tag.replace("instrument---", "") for tag in x if tag.startswith("instrument---")])

df_instruments = df_instruments.drop(columns=["tags"])

In [10]:
df_instruments.head(50)

,track_id,artist_id,album_id,path,duration,instruments
0,track_0000382,artist_000020,album_000046,82/382.mp3,211.1,[voice]
1,track_0000383,artist_000020,album_000046,83/383.mp3,113.1,[voice]
2,track_0000384,artist_000020,album_000046,84/384.mp3,115.7,[voice]
3,track_0000386,artist_000020,album_000046,86/386.mp3,103.4,[voice]
4,track_0000387,artist_000020,album_000046,87/387.mp3,257.1,[voice]
5,track_0000388,artist_000020,album_000046,88/388.mp3,124.6,[voice]
6,track_0000389,artist_000020,album_000046,89/389.mp3,150.8,[voice]
7,track_0000390,artist_000020,album_000046,90/390.mp3,133.7,[voice]
8,track_0000391,artist_000020,album_000046,91/391.mp3,82.1,[voice]
9,track_0000392,artist_000020,album_000046,92/392.mp3,127.3,[voice]
10,track_0000393,artist_000020,album_000046,93/393.mp3,132.2,[voice]
11,track_0000394,artist_000020,album_000046,94/394.mp3,143.2,[voice]
12,track_0000395,artist_000020,album_000046,95/395.mp3,111.3,[voice]
13,track_0000946,artist_000087,album_000149,46/946.mp3,241.7,[synthesizer]
14,track_0000947,artist_000087,album_000149,47/947.mp3,182.4,[synthesizer]
15,track_0000948,artist_000087,album_000149,48/948.mp3,212.7,[synthesizer]
16,track_0000949,artist_000087,album_000149,49/949.mp3,211.1,[synthesizer]
17,track_0000950,artist_000087,album_000149,50/950.mp3,248.0,[synthesizer]
18,track_0000951,artist_000087,album_000149,51/951.mp3,199.7,[synthesizer]
19,track_0000952,artist_000087,album_000149,52/952.mp3,291.1,[synthesizer]
20,track_0000953,artist_000087,album_000149,53/953.mp3,181.9,[synthesizer]
21,track_0000954,artist_000087,album_000149,54/954.mp3,218.5,[synthesizer]
22,track_0000955,artist_000087,album_000149,55/955.mp3,217.5,[synthesizer]
23,track_0000956,artist_000087,album_000149,56/956.mp3,380.1,[synthesizer]
24,track_0000957,artist_000087,album_000149,57/957.mp3,239.8,[synthesizer]
25,track_0000958,artist_000087,album_000149,58/958.mp3,247.0,[synthesizer]
26,track_0001268,artist_000209,album_000196,68/1268.mp3,235.9,[piano]
27,track_0002168,artist_000326,album_000347,68/2168.mp3,242.1,"[strings, synthesizer]"
28,track_0002171,artist_000326,album_000347,71/2171.mp3,259.1,"[beat, voice]"
29,track_0002966,artist_000441,album_000460,66/2966.mp3,198.8,[guitar]
30,track_0002967,artist_000441,album_000460,67/2967.mp3,259.4,[guitar]
31,track_0002968,artist_000441,album_000460,68/2968.mp3,270.2,[guitar]
32,track_0002969,artist_000441,album_000460,69/2969.mp3,168.8,[guitar]
33,track_0002970,artist_000441,album_000460,70/2970.mp3,175.4,[guitar]
34,track_0002971,artist_000441,album_000460,71/2971.mp3,239.0,[guitar]
35,track_0002972,artist_000441,album_000460,72/2972.mp3,239.7,[guitar]
36,track_0004887,artist_000696,album_000751,87/4887.mp3,251.7,[piano]
37,track_0004888,artist_000696,album_000751,88/4888.mp3,87.4,[guitar]
38,track_0004890,artist_000696,album_000751,90/4890.mp3,374.3,[piano]
39,track_0005087,artist_000696,album_000786,87/5087.mp3,109.1,[guitar]
40,track_0005090,artist_000696,album_000786,90/5090.mp3,163.3,[guitar]
41,track_0005760,artist_000789,album_000883,60/5760.mp3,281.8,[strings]
42,track_0006247,artist_000811,album_000960,47/6247.mp3,381.7,"[cello, keyboard, trombone]"
43,track_0006248,artist_000811,album_000960,48/6248.mp3,249.8,[piano]
44,track_0006249,artist_000811,album_000960,49/6249.mp3,364.7,"[keyboard, trombone]"
45,track_0006250,artist_000811,album_000960,50/6250.mp3,238.4,"[keyboard, trombone]"
46,track_0006251,artist_000811,album_000960,51/6251.mp3,392.4,"[keyboard, trombone]"
47,track_0006252,artist_000811,album_000960,52/6252.mp3,340.8,"[keyboard, trombone]"
48,track_0006253,artist_000811,album_000960,53/6253.mp3,271.8,"[cello, clarinet, doublebass, horn, keyboard, ..."
49,track_0006254,artist_000811,album_000960,54/6254.mp3,481.6,"[cello, clarinet, doublebass, horn, keyboard, ..."

In [11]:
df_instruments.shape

(25135, 6)

In [12]:
df_instruments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25135 entries, 0 to 25134
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   track_id     25135 non-null  object
 1   artist_id    25135 non-null  object
 2   album_id     25135 non-null  object
 3   path         25135 non-null  object
 4   duration     25135 non-null  float64
 5   instruments  25135 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.2+ MB

In [13]:
df_instruments.isna().sum()

track_id       0
artist_id      0
album_id       0
path           0
duration       0
instruments    0
dtype: int64

In [15]:
!ls data | grep genre

autotagging_genre.tsv

In [16]:
from collections import Counter

instrument_counts = Counter(
    instrument
    for instruments in df_instruments["instruments"]
    for instrument in instruments
)

pd.DataFrame(
    instrument_counts.items(),
    columns=["instrument", "count"]
).sort_values("count", ascending=False).head(20)

        instrument  count
2            piano   7750
1      synthesizer   7496
18           drums   6120
15            bass   5726
5           guitar   4804
19  electricguitar   4241
16        computer   2080
7         keyboard   2044
21  acousticguitar   1947
13          violin   1837
17     drummachine   1764
0            voice   1604
32   electricpiano   1282
3          strings   1278
6            cello   1114
20         sampler   1070
31      percussion    908
26       saxophone    891
12         trumpet    873
23           flute    859

In [17]:
rows = []

with open("data/autotagging_genre.tsv", "r", encoding="utf-8") as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.strip().split("\t")
        rows.append(parts)

data = []

for parts in rows[1:]:
    data.append({
        "track_id": parts[0],
        "artist_id": parts[1],
        "album_id": parts[2],
        "path": parts[3],
        "duration": float(parts[4]),
        "genres": [
            tag.replace("genre---", "")
            for tag in parts[5:]
            if tag.startswith("genre---")
        ]
    })

df_genres = pd.DataFrame(data)

In [18]:
df_genres.head()

,track_id,artist_id,album_id,path,duration,genres
0,track_0000214,artist_000014,album_000031,14/214.mp3,124.6,[punkrock]
1,track_0000215,artist_000014,album_000031,15/215.mp3,151.4,[metal]
2,track_0000216,artist_000014,album_000031,16/216.mp3,234.9,[metal]
3,track_0000217,artist_000014,album_000031,17/217.mp3,127.9,[punkrock]
4,track_0000218,artist_000014,album_000031,18/218.mp3,180.7,[punkrock]

In [19]:
df_genres.shape

(55215, 6)

In [20]:
df_genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55215 entries, 0 to 55214
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   track_id   55215 non-null  object
 1   artist_id  55215 non-null  object
 2   album_id   55215 non-null  object
 3   path       55215 non-null  object
 4   duration   55215 non-null  float64
 5   genres     55215 non-null  object
dtypes: float64(1), object(5)
memory usage: 2.5+ MB

In [21]:
df_genres.isna().sum()

track_id     0
artist_id    0
album_id     0
path         0
duration     0
genres       0
dtype: int64

In [22]:
all_genres = sorted({
    genre
    for genres in df_genres["genres"]
    for genre in genres
})

print("Количество жанров:", len(all_genres))
print(all_genres)

Количество жанров: 95
['60s', '70s', '80s', '90s', 'acidjazz', 'african', 'alternative', 'alternativerock', 'ambient', 'atmospheric', 'blues', 'bluesrock', 'bossanova', 'breakbeat', 'celtic', 'chanson', 'chillout', 'choir', 'classical', 'classicrock', 'club', 'contemporary', 'country', 'dance', 'darkambient', 'darkwave', 'deephouse', 'disco', 'downtempo', 'drumnbass', 'dub', 'dubstep', 'easylistening', 'edm', 'electronic', 'electronica', 'electropop', 'ethnicrock', 'ethno', 'eurodance', 'experimental', 'folk', 'funk', 'fusion', 'gothic', 'groove', 'grunge', 'hard', 'hardrock', 'heavymetal', 'hiphop', 'house', 'idm', 'improvisation', 'indie', 'industrial', 'instrumentalpop', 'instrumentalrock', 'jazz', 'jazzfunk', 'jazzfusion', 'latin', 'lounge', 'medieval', 'metal', 'minimal', 'newage', 'newwave', 'orchestral', 'oriental', 'pop', 'popfolk', 'poprock', 'postrock', 'progressive', 'psychedelic', 'punkrock', 'rap', 'reggae', 'rnb', 'rock', 'rocknroll', 'singersongwriter', 'ska', 'soul', 'soundtrack', 'swing', 'symphonic', 'synthpop', 'techno', 'trance', 'tribal', 'triphop', 'world', 'worldfusion']

In [23]:
genre_counts = Counter(
    genre
    for genres in df_genres["genres"]
    for genre in genres
)

pd.DataFrame(
    genre_counts.items(),
    columns=["genre", "count"]
).sort_values("count", ascending=False).head(20)

            genre  count
6      electronic  16480
30     soundtrack   8094
3             pop   7805
12        ambient   7570
2            rock   6865
4       classical   5602
7   easylistening   4833
24   experimental   3941
23    alternative   3761
13       chillout   3678
46          dance   2827
43         hiphop   2657
52          indie   2632
39           folk   2498
35     orchestral   2434
19           jazz   2371
8          lounge   2259
18         newage   2202
17         techno   2179
25        poprock   2172

In [24]:
rows = []

with open("data/autotagging_moodtheme.tsv", "r", encoding="utf-8") as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.strip().split("\t")
        rows.append(parts)

data = []

for parts in rows[1:]:
    data.append({
        "track_id": parts[0],
        "artist_id": parts[1],
        "album_id": parts[2],
        "path": parts[3],
        "duration": float(parts[4]),
        "moodtheme": [
            tag.replace("mood/theme---", "")
            for tag in parts[5:]
            if tag.startswith("mood/theme---")
        ]
    })

df_mood = pd.DataFrame(data)

In [25]:
df_mood.head()

,track_id,artist_id,album_id,path,duration,moodtheme
0,track_0000948,artist_000087,album_000149,48/948.mp3,212.7,[background]
1,track_0000950,artist_000087,album_000149,50/950.mp3,248.0,[background]
2,track_0000951,artist_000087,album_000149,51/951.mp3,199.7,[background]
3,track_0002165,artist_000326,album_000347,65/2165.mp3,229.0,[film]
4,track_0002263,artist_000320,album_000366,63/2263.mp3,494.7,[melancholic]

In [26]:
df_mood.shape

(18486, 6)

In [27]:
df_mood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18486 entries, 0 to 18485
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   track_id   18486 non-null  object
 1   artist_id  18486 non-null  object
 2   album_id   18486 non-null  object
 3   path       18486 non-null  object
 4   duration   18486 non-null  float64
 5   moodtheme  18486 non-null  object
dtypes: float64(1), object(5)
memory usage: 866.7+ KB

In [28]:
df_mood.isna().sum()

track_id     0
artist_id    0
album_id     0
path         0
duration     0
moodtheme    0
dtype: int64

In [29]:
df_tracks = df_genres.merge(
    df_instruments[["track_id", "instruments"]],
    on="track_id",
    how="inner"
)

df_tracks = df_tracks.merge(
    df_mood[["track_id", "moodtheme"]],
    on="track_id",
    how="left"
)

df_tracks.head()

,track_id,artist_id,album_id,path,duration,genres,instruments,moodtheme
0,track_0000382,artist_000020,album_000046,82/382.mp3,211.1,[classical],[voice],NaN
1,track_0000383,artist_000020,album_000046,83/383.mp3,113.1,[classical],[voice],NaN
2,track_0000384,artist_000020,album_000046,84/384.mp3,115.7,[classical],[voice],NaN
3,track_0000386,artist_000020,album_000046,86/386.mp3,103.4,[classical],[voice],NaN
4,track_0000387,artist_000020,album_000046,87/387.mp3,257.1,[classical],[voice],NaN

In [30]:
df_tracks.shape

(24894, 8)

In [31]:
df_tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24894 entries, 0 to 24893
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   track_id     24894 non-null  object
 1   artist_id    24894 non-null  object
 2   album_id     24894 non-null  object
 3   path         24894 non-null  object
 4   duration     24894 non-null  float64
 5   genres       24894 non-null  object
 6   instruments  24894 non-null  object
 7   moodtheme    10516 non-null  object
dtypes: float64(1), object(7)
memory usage: 1.5+ MB

In [32]:
df_tracks.isna().sum()

track_id           0
artist_id          0
album_id           0
path               0
duration           0
genres             0
instruments        0
moodtheme      14378
dtype: int64

Также MTG-Jamendo содержит ссылки на соответствующие аудиофайлы треков.
Аудиозаписи относятся к неструктурированным данным и могут использоваться
для последующего извлечения дополнительных акустических признаков.

In [49]:
df_tracks[["track_id", "path"]].head(10)

        track_id        path
0  track_0000382  82/382.mp3
1  track_0000383  83/383.mp3
2  track_0000384  84/384.mp3
3  track_0000386  86/386.mp3
4  track_0000387  87/387.mp3
5  track_0000388  88/388.mp3
6  track_0000389  89/389.mp3
7  track_0000390  90/390.mp3
8  track_0000391  91/391.mp3
9  track_0000392  92/392.mp3

##MusicBrainz (XML)

In [33]:
url = "https://musicbrainz.org/ws/2/recording/"
params = {
    "query": 'recording:"Yellow" AND artist:"Coldplay"',
    "fmt": "xml"
}

headers = {
    "User-Agent": "MusicCoursework/1.0"
}

response = requests.get(url, params=params, headers=headers)

print(response.status_code)

200

In [34]:
print(response.text[:2000])

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><metadata created="2026-10-09T14:34:55.103Z" xmlns="http://musicbrainz.org/ns/mmd-2.0#" xmlns:ns2="http://musicbrainz.org/ns/ext#-2.0"><recording-list count="146" offset="0"><recording id="4352d312-6e75-42a4-bf0d-574abb922719" ns2:score="100"><title>Yellow</title><length>329000</length><disambiguation>live, 2003-07-22: Horden Pavillion, Sydney, Australia</disambiguation><artist-credit id="d97213b4-e672-3cde-9e53-6870e168f6ae"><name-credit><name>Coldplay</name><artist id="cc197bad-dc9c-440d-a5b5-d52ba2e14234"><name>Coldplay</name><sort-name>Coldplay</sort-name><alias-list><alias sort-name="Coolplay" type="Search hint" type-id="1937e404-b981-3cb7-8151-4c86ebfc8d8e">Coolplay</alias><alias sort-name="콜드플레이" type="Search hint" type-id="1937e404-b981-3cb7-8151-4c86ebfc8d8e">콜드플레이</alias><alias locale="ja" sort-name="コールドプレイ" type="Artist name" type-id="894afba6-2816-3c24-8072-eadb66bd04bc">コールドプレイ</alias><alias sort-name="Cold Play" type="Search hint" type-id="1937e404-b981-3cb7-8151-4c86ebfc8d8e">Cold Play</alias><alias sort-name="Coldplay, The" type="Artist name" type-id="894afba6-2816-3c24-8072-eadb66bd04bc" end-date="1998">The Coldplay</alias></alias-list></artist></name-credit></artist-credit><release-list><release id="f652f463-9825-43f0-8267-365bf7a08485"><title>2003-07-22: Horden Pavillion, Sydney, Australia</title><status id="1156806e-d06a-38bd-83f0-cf2284a808b9">Bootleg</status><artist-credit id="d97213b4-e672-3cde-9e53-6870e168f6ae"><name-credit><name>Coldplay</name><artist id="cc197bad-dc9c-440d-a5b5-d52ba2e14234"><name>Coldplay</name><sort-name>Coldplay</sort-name></artist></name-credit></artist-credit><release-group id="a743767b-085f-4106-90eb-7f79656abf7e" type="Live" type-id="6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"><title>2003-07-22: Horden Pavillion, Sydney, Australia</title><primary-type id="f529b476-6e62-324f-b0aa-1f3e33d313fc">Album</primary-type><secondary-type-list><secondary-type id="6fd474e2-6b58-

In [35]:
root = ET.fromstring(response.text)
root.tag

'{http://musicbrainz.org/ns/mmd-2.0#}metadata'

In [36]:
ns = {
    "m": "http://musicbrainz.org/ns/mmd-2.0#"
}

recordings = root.findall(".//m:recording", ns)

len(recordings)

25

In [37]:
recordings[0].find("m:title", ns).text

'Yellow'

In [38]:
musicbrainz_rows = []

for recording in recordings:
    title = recording.find("m:title", ns)

    musicbrainz_rows.append({
        "recording_id": recording.attrib.get("id"),
        "title": title.text if title is not None else None
    })

df_musicbrainz = pd.DataFrame(musicbrainz_rows)

In [39]:
df_musicbrainz.head(25)

                            recording_id   title
0   4352d312-6e75-42a4-bf0d-574abb922719  Yellow
1   2e30d825-55ad-4d8c-a527-50e4a1909568  Yellow
2   a33d09b1-7ee3-4077-9c56-597dee535434  Yellow
3   98f07927-221f-452f-bf5d-65340849574d  Yellow
4   da97b6cb-68ff-4f2a-b726-29c8ddb2668e  Yellow
5   e663d2b8-1309-4f80-8495-1fb17e23f9c6  Yellow
6   1e75db0a-bb43-458c-8cc3-dbd997422bc1  Yellow
7   507b12aa-9ee9-4aa8-a741-b4edaa1d826e  Yellow
8   935b8767-ec6f-4a10-9987-1ebdaf068fe9  Yellow
9   447f9d36-7754-43ae-9c7f-3e0fd9e29a8b  Yellow
10  1613176e-0ffe-451a-8302-0dcfb5e27f09  Yellow
11  fc6f85a3-b614-4045-8cdc-15827ccc8ed4  Yellow
12  5bb81063-911d-4e32-8221-59690e18252a  Yellow
13  900ea533-b6d5-455e-8cad-20ffbd395e69  Yellow
14  721f10e5-a841-4c4a-b9ea-5732b3bfb8ba  Yellow
15  a7966633-8612-4bab-8cf2-06a820398633  Yellow
16  b007b746-13fb-4a58-be16-87d25fefd3e5  Yellow
17  b116578f-c61a-4f78-afc7-8fee0ea6ee7a  Yellow
18  64105f2d-4956-4cb4-ab1a-d4c9c910277a  Yellow
19  b7dae43e-df17-4e16-8526-368c54e1728b  Yellow
20  aa220182-5cc2-47cf-b568-04a78bac1c74  Yellow
21  f7c3bfe7-4a0c-4e07-9b55-a53b1ecb3d22  Yellow
22  642584d5-dafc-4235-9765-d09992bb9aa3  Yellow
23  e3a5e3ed-50a6-4fd9-87a6-ef17d8f89369  Yellow
24  9a9904c0-c2e9-42a6-b442-1406bf8bafa5  Yellow

In [40]:
df_musicbrainz.shape

(25, 2)

In [41]:
df_musicbrainz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   recording_id  25 non-null     object
 1   title         25 non-null     object
dtypes: object(2)
memory usage: 532.0+ bytes

##Last.fm (API)

In [42]:
LASTFM_API_KEY = '''api_key'''

url = "https://ws.audioscrobbler.com/2.0/"

params = {
    "method": "track.getInfo",
    "api_key": LASTFM_API_KEY,
    "artist": "Coldplay",
    "track": "Yellow",
    "format": "json"
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [43]:
data = response.json()
data

{'track': {'name': 'Yellow',
  'mbid': '0063bb06-4e74-464d-97ae-b82f90bcb222',
  'url': 'https://www.last.fm/music/Coldplay/_/Yellow',
  'duration': '266000',
  'streamable': {'#text': '0', 'fulltrack': '0'},
  'listeners': '3665825',
  'playcount': '40432963',
  'artist': {'name': 'Coldplay',
   'mbid': 'cc197bad-dc9c-440d-a5b5-d52ba2e14234',
   'url': 'https://www.last.fm/music/Coldplay'},
  'album': {'artist': 'Coldplay',
   'title': 'Parachutes',
   'url': 'https://www.last.fm/music/Coldplay/Parachutes',
   'image': [{'#text': 'https://lastfm-img.freetls.fastly.net/i/u/34s/5fbcfb7258117e88cb73b45e25c88b01.png',
     'size': 'small'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/64s/5fbcfb7258117e88cb73b45e25c88b01.png',
     'size': 'medium'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/174s/5fbcfb7258117e88cb73b45e25c88b01.png',
     'size': 'large'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/300x300/5fbcfb7258117e88cb73b45e25c88b01.png',
     'size': 'extralarge'}]},
  'toptags': {'tag': [{'name': 'rock', 'url': 'https://www.last.fm/tag/rock'},
    {'name': 'alternative', 'url': 'https://www.last.fm/tag/alternative'},
    {'name': 'Coldplay', 'url': 'https://www.last.fm/tag/Coldplay'},
    {'name': 'alternative rock',
     'url': 'https://www.last.fm/tag/alternative+rock'},
    {'name': 'britpop', 'url': 'https://www.last.fm/tag/britpop'}]},
  'wiki': {'published': '21 Jun 2008, 16:01',
   'summary': '"Yellow" is a song by English alternative rock band Coldplay. The band wrote the song and co-produced it with British record producer Ken Nelson for their debut album, Parachutes. The song\'s lyrics are a reference to band vocalist Chris Martin\'s unrequited love, and its musicscape is built on a varied instrumentation.\n\nThe song was released in June 2000 as the second single off the album, following Shiver, and the lead single in the United States. <a href="http://www.last.fm/music/Coldplay/_/Yellow">Read more on Last.fm</a>.',
   'content': '"Yellow" is a song by English alternative rock band Coldplay. The band wrote the song and co-produced it with British record producer Ken Nelson for their debut album, Parachutes. The song\'s lyrics are a reference to band vocalist Chris Martin\'s unrequited love, and its musicscape is built on a varied instrumentation.\n\nThe song was released in June 2000 as the second single off the album, following Shiver, and the lead single in the United States. The single reached #4 in the UK Singles Chart, giving the band their first top-5 hit in the United Kingdom.\n\nHelped by heavy rotation and usage in promotions, the song thrust the band into massive popularity. Yellow has since been covered by various recording artists worldwide, and remains one of the band\'s most popular songs.\n\nWhile composing the song\'s lyrics, however, Chris Martin could not find the right words. He was thinking of a specific word, which he deemed a missing key word in the lyrics, to fit the song\'s concept. He looked around the studio and found the telephone directory Yellow Pages, which happened to be situated nearest to him. Chris Martin later titled the song \'Yellow\' as a reference to the directory. But according to him, "In an alternate universe, this song could be called \'Playboy\'." The lyrics progressed from there with the band collaborating. The band\'s bassist Guy Berryman came up with the opening line "Look at the stars". That night, having quickly composed the song, the band recorded it. <a href="http://www.last.fm/music/Coldplay/_/Yellow">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [44]:
track = data["track"]

print("Название:", track["name"])
print("Исполнитель:", track["artist"]["name"])
print("Listeners:", track["listeners"])
print("Playcount:", track["playcount"])

Название: Yellow
Исполнитель: Coldplay
Listeners: 3665825
Playcount: 40432963

In [45]:
tags = [tag["name"] for tag in track["toptags"]["tag"]]
tags

['rock', 'alternative', 'Coldplay', 'alternative rock', 'britpop']

In [46]:
df_lastfm = pd.DataFrame([{
    "track": track["name"],
    "artist": track["artist"]["name"],
    "listeners": int(track["listeners"]),
    "playcount": int(track["playcount"]),
    "tags": tags
}])

df_lastfm

,track,artist,listeners,playcount,tags
0,Yellow,Coldplay,3665825,40432963,"[rock, alternative, Coldplay, alternative rock..."



1. **MTG-Jamendo** — табличные данные о музыкальных треках,
   включающие длительность, жанры, инструменты и mood/theme.
   Таблицы связаны по идентификатору `track_id`.

2. **MusicBrainz API** — источник иерархических данных в формате XML.
   Используется для получения метаданных о музыкальных записях.

3. **Last.fm API** — источник данных в формате JSON.
   Позволяет получать количество слушателей, количество прослушиваний
   и пользовательские теги музыкальных треков.

Числовые характеристики: длительность, listeners, playcount.

Категориальные характеристики: жанр, инструменты, mood/theme,
исполнитель и пользовательские теги.